"""Export the final high-precision MTC audit ledger as Markdown."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Sequence

import mpmath

if __package__ in {None, ""}:  # pragma: no cover - direct script execution convenience.
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from mtc_engine.bridge_audit import (  # noqa: E402
    AUDIT_DPS,
    NOISE_WALL,
    BridgeAuditReport,
    OffShellPerturbationAudit,
    audit_bridge_precision,
    simulate_off_shell_coordinate_perturbation,
)
from mtc_engine.parent_subspace import (  # noqa: E402
    PARENT_SUBSPACE_NOISE_WALL,
    ParentSubspaceReport,
    solve_parent_subspace,
)


DEFAULT_OUTPUT_PATH = Path("results/final_audit_report.md")
DEFAULT_DELTAS = ("1e-40", "1e-60", "1e-80")
DEFAULT_SWEEP_PARAMETERS = (
    "parent_level",
    "lepton_level",
    "quark_level",
    "capacity_bits",
    "kappa_d5",
)


def build_parser() -> argparse.ArgumentParser:
    """Build the report-export command-line interface."""

    parser = argparse.ArgumentParser(
        prog="mtc-export-report",
        description="Export the final high-precision MTC audit ledger as Markdown.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Markdown output path. Parent directories are created automatically.",
    )
    parser.add_argument(
        "--dps",
        type=int,
        default=AUDIT_DPS,
        help="Decimal digits for all high-precision evaluations. Values below 250 are promoted.",
    )
    parser.add_argument(
        "--delta",
        action="append",
        default=[],
        help="Perturbation delta string for the stiffness sweep. May be supplied multiple times.",
    )
    parser.add_argument(
        "--parameter",
        action="append",
        default=[],
        help="Topological coordinate to sweep. May be supplied multiple times.",
    )
    return parser


def export_final_audit_report(
    output_path: Path = DEFAULT_OUTPUT_PATH,
    *,
    dps: int = AUDIT_DPS,
    deltas: Sequence[str] = DEFAULT_DELTAS,
    parameters: Sequence[str] = DEFAULT_SWEEP_PARAMETERS,
) -> Path:
    """Run all public audit channels and export a Markdown ledger."""

    resolved_dps = max(AUDIT_DPS, int(dps))
    mpmath.mp.dps = resolved_dps
    with mpmath.workdps(resolved_dps):
        bridge_report = audit_bridge_precision(dps=resolved_dps)
        parent_report = solve_parent_subspace(dps=resolved_dps)
        sweep = _stiffness_sweep(parameters=parameters, deltas=deltas, dps=resolved_dps)
        markdown = render_markdown_report(
            bridge_report,
            parent_report,
            sweep,
            dps=resolved_dps,
            deltas=deltas,
            parameters=parameters,
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    return output_path


def render_markdown_report(
    bridge_report: BridgeAuditReport,
    parent_report: ParentSubspaceReport,
    sweep: Sequence[OffShellPerturbationAudit],
    *,
    dps: int,
    deltas: Sequence[str],
    parameters: Sequence[str],
) -> str:
    """Render the combined audit state as a strict Category A/B Markdown ledger."""

    lines: list[str] = [
        "# Spectral-Invariants-MTC Final Audit Ledger",
        "",
        "This file is generated by `mtc_engine.export_report` using high-precision `mpmath` arithmetic only; no binary double-precision down-casts are used.",
        "",
        "## Run Configuration",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Overall bridge status | {_status(bridge_report.passed)} |",
        f"| Parent subspace status | {_status(parent_report.passed)} |",
        f"| Stiffness sweep status | {_status(all(response.passed for response in sweep))} |",
        f"| `mpmath.mp.dps` | `{dps}` |",
        f"| Bridge noise wall | {_code(NOISE_WALL, dps)} |",
        f"| Parent-subspace noise wall | {_code(PARENT_SUBSPACE_NOISE_WALL, dps)} |",
        f"| Constants source | `{bridge_report.completion.source.as_posix()}` |",
        f"| `c_dark` exact | {_code(bridge_report.completion.c_dark, dps)} |",
    ]
    if bridge_report.completion.display_value is not None:
        lines.append(f"| `c_dark` display | {_code(bridge_report.completion.display_value, dps)} |")
    if bridge_report.completion.display_rounding_residue is not None:
        lines.append(
            f"| Display rounding residue | {_code(bridge_report.completion.display_rounding_residue, dps)} |"
        )

    lines.extend(
        [
            "",
            "## Executive Validation Summary",
            "",
            "| Channel | Taxonomy | Status | Validation output |",
            "| --- | --- | --- | --- |",
            _summary_row(
                "Visible branch framing arithmetic",
                "Category A",
                all(zero.passed for zero in bridge_report.phase_zeros if zero.label != "mass_gap_quarter_power"),
                "Exact Fraction-level relations and phase residuals vanish.",
            ),
            _summary_row(
                "Tractable Frobenius-Perron sectors",
                "Category A",
                all(check.passed for check in bridge_report.frobenius_perron if check.sector_name != "SO(10)_312"),
                "Small-sector quantum dimensions agree with Perron data.",
            ),
            _summary_row(
                "SO(10)_312 parent subspace",
                "Category B",
                parent_report.passed,
                "Targeted four-block Weyl/Kac-Peterson validation bypasses full-spectrum enumeration.",
            ),
            _summary_row(
                "Loop trace and mass-gap closure",
                "Category B",
                bridge_report.loop_trace.passed,
                "Diagonal trace, modular-T, and quartic trace closures lie below the wall.",
            ),
            _summary_row(
                "Continuous-coordinate stiffness",
                "Category B",
                all(response.passed for response in sweep),
                "Every nonzero sweep perturbation recomputes a finite VOA defect and infinite bulk norm.",
            ),
        ]
    )

    _append_category_a(lines, bridge_report, dps=dps)
    _append_category_b(lines, bridge_report, parent_report, sweep, dps=dps, deltas=deltas, parameters=parameters)

    lines.extend(
        [
            "",
            "## Final Sentinel",
            "",
            "```text",
            "[SPECTRAL CLOSURE VALIDATED]" if bridge_report.passed and parent_report.passed else "[SPECTRAL CLOSURE FAILED]",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _append_category_a(lines: list[str], bridge_report: BridgeAuditReport, *, dps: int) -> None:
    lines.extend(
        [
            "",
            "## Category A — Topological Foundations",
            "",
            "Category A contains non-circular topological inputs: exact visible-branch arithmetic and tractable small-sector Frobenius-Perron validations.",
            "",
            "### Exact Visible-Branch Framing Arithmetic",
            "",
            "| Relation | Value | Integer target | Exact residual | Phase residual | Normalized residual | Status |",
            "| --- | ---: | ---: | ---: | ---: | ---: | --- |",
        ]
    )
    for zero in bridge_report.phase_zeros:
        if zero.label == "mass_gap_quarter_power":
            continue
        lines.append(
            "| "
            f"`{zero.label}` | `{zero.relation}` | `{zero.integer_target}` | `{zero.diophantine_residual}` | "
            f"{_code(zero.phase_residual, dps)} | {_code(zero.normalized_residual, dps)} | {_status(zero.passed)} |"
        )

    lines.extend(
        [
            "",
            "### Tractable Frobenius-Perron Extractions",
            "",
            "| Sector | Primary | Verification | Eigenvalue | Quantum dimension | Residual | Residual / `c_dark` | Status |",
            "| --- | --- | --- | ---: | ---: | ---: | ---: | --- |",
        ]
    )
    for check in bridge_report.frobenius_perron:
        if check.sector_name == "SO(10)_312":
            continue
        verification = "full fusion matrix" if check.matrix_verified else "Verlinde/Weyl dimension formula"
        lines.append(
            "| "
            f"`{check.sector_name}` | `{check.primary}` | {verification} | {_code(check.eigenvalue, dps)} | "
            f"{_code(check.quantum_dimension, dps)} | {_code(check.residual, dps)} | "
            f"{_code(check.normalized_residual, dps)} | {_status(check.passed)} |"
        )


def _append_category_b(
    lines: list[str],
    bridge_report: BridgeAuditReport,
    parent_report: ParentSubspaceReport,
    sweep: Sequence[OffShellPerturbationAudit],
    *,
    dps: int,
    deltas: Sequence[str],
    parameters: Sequence[str],
) -> None:
    loop = bridge_report.loop_trace
    lines.extend(
        [
            "",
            "## Category B — Internal Consistency Validation",
            "",
            "Category B contains internal closure validations: parent-sector self-consistency, trace identities, mass-gap algebra, precision residual logs, and continuous-coordinate rigidity probes.",
            "",
            "### SO(10)_312 Parent-Subspace Solver",
            "",
            "| Field | Value |",
            "| --- | --- |",
            f"| Status | {_status(parent_report.passed)} |",
            f"| Full parent primary count | `{parent_report.full_parent_primary_count}` |",
            f"| Audited block order | `{', '.join(parent_report.block_order)}` |",
            f"| Capacity bits | {_code(parent_report.capacity_bits, dps)} |",
            f"| Modular-S submatrix shape | `{len(parent_report.modular_s_submatrix)} x {len(parent_report.modular_s_submatrix[0])}` |",
            "",
            "| Block | Weight | Weyl quantum dimension | Core quantum dimension | Dimension residual | Character residual | Status |",
            "| --- | --- | ---: | ---: | ---: | ---: | --- |",
        ]
    )
    for block in parent_report.blocks:
        lines.append(
            "| "
            f"`{block.label}` | `{block.weight}` | {_code(block.quantum_dimension, dps)} | "
            f"{_code(block.core_quantum_dimension, dps)} | {_code(block.dimension_residual, dps)} | "
            f"{_code(block.character_dimension_residual, dps)} | {_status(block.passed)} |"
        )

    lines.extend(
        [
            "",
            "#### Targeted Parent Modular-S Submatrix",
            "",
            "This 4×4 matrix is evaluated directly on the audited parent blocks and never materializes the 6,563,729,615-primary parent spectrum.",
            "",
        ]
    )
    lines.extend(_markdown_matrix(parent_report.block_order, parent_report.modular_s_submatrix, dps=dps))

    lines.extend(
        [
            "",
            "### Massive Parent-Sector Frobenius-Perron Self-Consistency",
            "",
            "| Sector | Primary | Classification | Eigenvalue | Quantum dimension | Residual | Residual / `c_dark` | Status |",
            "| --- | --- | --- | ---: | ---: | ---: | ---: | --- |",
        ]
    )
    for check in bridge_report.frobenius_perron:
        if check.sector_name != "SO(10)_312":
            continue
        lines.append(
            "| "
            f"`{check.sector_name}` | `{check.primary}` | internal algebraic self-comparison | "
            f"{_code(check.eigenvalue, dps)} | {_code(check.quantum_dimension, dps)} | "
            f"{_code(check.residual, dps)} | {_code(check.normalized_residual, dps)} | {_status(check.passed)} |"
        )

    lines.extend(
        [
            "",
            "### Loop Trace and Diagonal-Trace Identities",
            "",
            "| Field | Value |",
            "| --- | --- |",
            f"| Parent trace sector | `{loop.parent_trace.sector_name}` |",
            f"| Parent primary count | `{loop.parent_trace.primary_count}` |",
            f"| Parent torus trace | {_code(loop.parent_trace.value, dps)} |",
            f"| Modular-T reference trace | {_code(loop.modular_t.reference_value, dps)} |",
            f"| Modular-T transformed trace | {_code(loop.modular_t.transformed_value, dps)} |",
            f"| Modular-T residual | {_code(loop.modular_t.residual, dps)} |",
            f"| Diagonal modulus residual | {_code(loop.modular_t.diagonal_modulus_residual, dps)} |",
            f"| `c_dark` weighted residual | {_code(loop.completion_weighted_residue, dps)} |",
            f"| Weighted residual / `c_dark` | {_code(loop.normalized_residue, dps)} |",
            f"| Status | {_status(loop.passed)} |",
            "",
            "### Mass-Gap Scaling Identity",
            "",
            "| Field | Value |",
            "| --- | --- |",
        ]
    )
    for zero in bridge_report.phase_zeros:
        if zero.label != "mass_gap_quarter_power":
            continue
        lines.extend(
            [
                f"| Exponent identity label | `{zero.label}` |",
                f"| Exponent identity relation | `{zero.relation}` |",
                f"| Exponent exact residual | `{zero.diophantine_residual}` |",
                f"| Exponent normalized residual | {_code(zero.normalized_residual, dps)} |",
            ]
        )
    lines.extend(
        [
            f"| Mass-gap exponent | `{loop.mass_gap.scaling_exponent}` |",
            f"| Mass-gap value | {_code(loop.mass_gap.mass_gap, dps)} |",
            f"| Mass-gap closure residual | {_code(loop.mass_gap.closure_residual, dps)} |",
            f"| Status | {_status(loop.mass_gap.passed)} |",
            "",
            "### High-Precision Error Log",
            "",
            "| Label | Residual | Normalized residual | Wall | Status | Detail |",
            "| --- | ---: | ---: | ---: | --- | --- |",
        ]
    )
    for entry in bridge_report.error_log.entries:
        lines.append(
            "| "
            f"`{entry.label}` | {_code(entry.residual, dps)} | {_code(entry.normalized_residual, dps)} | "
            f"{_code(entry.noise_wall, dps)} | {_status(entry.passed)} | {entry.detail} |"
        )

    _append_stiffness_sweep(lines, sweep, dps=dps, deltas=deltas, parameters=parameters)


def _append_stiffness_sweep(
    lines: list[str],
    sweep: Sequence[OffShellPerturbationAudit],
    *,
    dps: int,
    deltas: Sequence[str],
    parameters: Sequence[str],
) -> None:
    lines.extend(
        [
            "",
            "### Continuous-Coordinate Perturbation Sweep",
            "",
            "The sweep recomputes the finite VOA closure tensor before lifting to the singleton-moduli bulk norm. A nonzero finite defect with zero tangent norm yields an infinite stiffness response.",
            "",
            f"- Swept coordinates: `{', '.join(parameters)}`",
            f"- Swept deltas: `{', '.join(deltas)}`",
            "",
            "| Coordinate | Delta | Finite defect norm | Tangent norm | Closure tensor norm | Root displacement | Integer residual | Framing phase residual | Prefactor residual | Capacity residual | Accepted | Diverged | Status |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | --- |",
        ]
    )
    for response in sweep:
        tensor = response.closure_tensor
        lines.append(
            "| "
            f"`{response.parameter}` | {_code(response.perturbation, dps)} | {_code(tensor.finite_norm, dps)} | "
            f"{_code(tensor.tangent_norm, dps)} | {_code(response.closure_tensor_norm, dps)} | "
            f"{_code(tensor.root_metric_displacement, dps)} | {_code(tensor.level_integrality_residual, dps)} | "
            f"{_code(tensor.framing_phase_residual, dps)} | {_code(tensor.prefactor_residual, dps)} | "
            f"{_code(tensor.capacity_residual, dps)} | `{response.accepted}` | `{response.diverged}` | {_status(response.passed)} |"
        )


def _stiffness_sweep(
    *,
    parameters: Sequence[str],
    deltas: Sequence[str],
    dps: int,
) -> tuple[OffShellPerturbationAudit, ...]:
    return tuple(
        simulate_off_shell_coordinate_perturbation(parameter, delta, dps=dps)
        for parameter in parameters
        for delta in deltas
    )


def _markdown_matrix(
    labels: Sequence[str],
    matrix: Sequence[Sequence[mpmath.mpc]],
    *,
    dps: int,
) -> list[str]:
    header = "| Row | " + " | ".join(f"`{label}`" for label in labels) + " |"
    separator = "| --- | " + " | ".join("---:" for _ in labels) + " |"
    rows = [header, separator]
    for label, row in zip(labels, matrix):
        rows.append("| " + f"`{label}` | " + " | ".join(_code(entry, dps) for entry in row) + " |")
    return rows


def _summary_row(channel: str, taxonomy: str, passed: bool, detail: str) -> str:
    return f"| {channel} | {taxonomy} | {_status(passed)} | {detail} |"


def _code(value: object, digits: int) -> str:
    return f"`{_format_decimal(value, digits)}`"


def _format_decimal(value: object, digits: int) -> str:
    """Format high-precision values without any binary-float conversion."""

    if isinstance(value, mpmath.mpc):
        real = _format_decimal(mpmath.re(value), digits)
        imaginary = _format_decimal(abs(mpmath.im(value)), digits)
        sign = "+" if mpmath.im(value) >= 0 else "-"
        return f"({real} {sign} {imaginary}i)"
    if isinstance(value, mpmath.mpf):
        if mpmath.isinf(value):
            return "+inf" if value > 0 else "-inf"
        if mpmath.isnan(value):
            return "nan"
        fixed_window = digits * 4
        return mpmath.nstr(
            value,
            n=digits,
            strip_zeros=False,
            min_fixed=-fixed_window,
            max_fixed=fixed_window,
        )
    return str(value)


def _status(passed: bool) -> str:
    return "PASS" if passed else "FAIL"


def main(argv: Sequence[str] | None = None) -> int:
    """Run the report exporter and return a process exit code."""

    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    if args.dps <= 0:
        parser.error("--dps must be positive")

    deltas = tuple(args.delta) if args.delta else DEFAULT_DELTAS
    parameters = tuple(args.parameter) if args.parameter else DEFAULT_SWEEP_PARAMETERS
    output_path = export_final_audit_report(args.output, dps=args.dps, deltas=deltas, parameters=parameters)
    print(f"Exported final audit report to {output_path.as_posix()}")
    return 0


__all__ = [
    "DEFAULT_DELTAS",
    "DEFAULT_OUTPUT_PATH",
    "DEFAULT_SWEEP_PARAMETERS",
    "build_parser",
    "export_final_audit_report",
    "main",
    "render_markdown_report",
]


if __name__ == "__main__":
    raise SystemExit(main())
